name: Публикация релиза

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    uses: autumn-library/workflows/.github/workflows/release.yml@main
    with:
      package_mask: "winow-*.ospx"
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
